language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -c exaanalytics exa
  - conda install --yes -c conda-forge pytables nodejs
  - conda install --yes numba psutil numexpr
  - pip install travis-sphinx codacy-coverage python-coveralls codecov
  - pip install sphinxcontrib-autoanysrc sphinx_rtd_theme
  - python setup.py install
  - exa -uu
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
