language: python

os:
  - linux

python:
<<<<<<< HEAD
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - git clone https://github.com/avmarchenko/exa.git ../exa

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION
  - conda install -q -c conda-forge `cat ../exa/requirements.txt`
  - conda install -q -c conda-forge pytables
  - pip install sphinxcontrib-autoanysrc coverage codecov python-coveralls
  - cd ../exa; pip install .; cd ../exatomic;
  - pip install . 

=======
  - "3.4"
  - "3.5"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -c exaanalytics exa exawidgets
  - conda install --yes -c conda-forge pytables
  - conda install --yes numba psutil numexpr
  - conda install --yes -c cpcloud npm
  - pip install travis-sphinx codacy-coverage python-coveralls codecov
  - pip install sphinxcontrib-autoanysrc sphinx_rtd_theme
  - python setup.py install
  - exa -uu
>>>>>>> org/master
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build
<<<<<<< HEAD

=======
>>>>>>> org/master
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
<<<<<<< HEAD
  - travis-sphinx deploy
=======
  - travis-sphinx -n deploy
>>>>>>> org/master
