language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - git clone https://github.com/avmarchenko/exa
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install -c conda-forge --yes jupyter notebook ipywidgets ipyparallel
  - conda install --yes numba
  - conda install --yes -c exaanalytics exa
  - pip install sphinxcontrib-autoanysrc coverage codecov python-coveralls
  - python setup.py install
  - exa -uu
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx build
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx deploy
