language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - deactivate
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export NUMBA_DISABLE_JIT=1
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q -c conda-forge 'icu=56.*'

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
# 3.9 DEV
  - git clone https://github.com/exa-analytics/exa.git
  - cd exa
  - git fetch origin pull/139/head:org-master-3.9
  - git checkout org-master-3.9
  - conda install -q -c conda-forge `cat requirements.txt`
  - conda install -q -c conda-forge pytables python-coveralls ply pandoc pypandoc nbsphinx
  - pip install travis-sphinx codacy-coverage coverage
  - pip install .
  - cd ../
# - conda install -q -c exaanalytics exa
  - conda install -q -c conda-forge psutil numexpr nodejs ipywidgets
  - pip install .

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
