package:
    name: exatomic
<<<<<<< HEAD
    version: "0.4.0.dev0"

app:
    entry: exatomic

source:
    git_rev: v0.4.0.dev0
=======
    version: "0.3.8"

source:
    git_rev: v0.3.8
>>>>>>> org/master
    git_url: https://github.com/exa-analytics/exatomic.git

requirements:
    build:
        - python x.x
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose
        - numba
        - exa
        - exawidgets

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose
        - numba
        - exa
        - exawidgets

about:
    home: https://exa-analytics.github.io
    license: Apache 2.0
    license_file: LICENSE
    summary: A unified platform for computational chemists.
