<<<<<<< HEAD
{% set name = "exatomic" %}
{% set version = "0.4.0" %}
=======
{% set name = "exa" %}
{% set version = "0.3.9" %}
>>>>>>> 1c37655b6be3dca60b2adbeee8ca3767e5477943
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - networkx
<<<<<<< HEAD
    - paramiko
    - pandas
    - sympy
=======
    - pandas
>>>>>>> 1c37655b6be3dca60b2adbeee8ca3767e5477943
    - notebook
    - nose
    - numba
    - six
    - pytables
    - sphinx
    - sphinx_rtd_theme
    - pandoc
    - nbsphinx
<<<<<<< HEAD
    - exa

test:
  imports:
    - exatomic
=======

test:
  imports:
    - exa
>>>>>>> 1c37655b6be3dca60b2adbeee8ca3767e5477943

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
<<<<<<< HEAD
    summary: A unified platform for theoretical and computational chemists.
=======
    summary: A framework for data processing, computation, and visualization.
>>>>>>> 1c37655b6be3dca60b2adbeee8ca3767e5477943
