{% set name = "exatomic" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - PyYAML>=3.0
    - bokeh
    - h5py>=3.4.0
    - ipywidgets>=7.0
    - matplotlib>=3.0
    - networkx>=2.0
    - numba>=0.50
    - numexpr>=2.0
    - numpy>=1.0
    - pandas>=1.0.5
    - scipy>=1.4
    - seaborn>=0.10
    - six>=1.0
    - sympy>=1.5
    - pytables>=3.6

test:
  imports:
    - {{ name }}

about:
    home: https://github.com/exa-analytics/{{ name }}.git
    license: Apache-2.0
    license_file: LICENSE
    summary: A unified platform for theoretical and computational chemists
