package:
    name: exatomic
    version: "0.3.2"

source:
    git_rev: v0.3.2
    git_url: https://github.com/exa-analytics/exatomic.git

requirements:
    build:
        - python x.x
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose
        - exa

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose
        - exa

about:
    home: https://exa-analytics.github.io
    license: Apache 2.0
    license_file: LICENSE
    summary: A unified platform for computational chemists.
