{% set name = "exatomic" %}
{% set version = "0.3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - networkx
    - pandas
    - notebook
    - nose
    - numba
    - six
    - pytables
    - sphinx
    - sphinx_rtd_theme
    - pandoc
    - nbsphinx
    - exa
    - sympy
    - symengine

test:
  imports:
    - exatomic

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
    summary: A unified platform for theoretical and computational chemists.
