{% set name = "exatomic" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - exa
    - ipywidgets>=7.0
    - numexpr>=2.0

test:
  imports:
    - {{ name }}

about:
    home: https://github.com/exa-analytics/{{ name }}.git
    license: Apache-2.0
    license_file: LICENSE
    summary: A unified platform for theoretical and computational chemists
