name: Upload codacy coverage
inputs:
  project-token:
    required: true
    description: "API project token to authenticate on the Codacy API while uploading the coverage data"
  coverage-reports:
    description: 'Optional comma separated list of coverage reports to send to Codacy'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1

