name: Publish Conda Artifacts
description: Publish conda artifacts for different architectures
inputs:
  python-version:
    description: 'Python version to build'
    required: true
    default: '3.8'
  conda-username:
    description: 'Username for conda channel access'
    required: true
    default: 'user'
  conda-password:
    description: 'Password for conda channel access'
    required: true
    default: 'password'
runs:
  using: 'composite'
  steps:
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        channels: conda-forge
    - name: Install Release Dependencies
      shell: bash -l {0}
      run: |
        conda install `cat requirements.txt | sed "s/tables/pytables/"`
        conda install `cat requirements.dev.txt`
        conda install `cat requirements.release.txt`
        pip install -e .
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: project-artifact-${{ inputs.python-version }}
        path: dist/
    - name: Publish To Conda
      shell: bash -l {0}
      run: |
        ls dist/*
        PYTHONVER=${{ inputs.python-version }}
        pyver="py${PYTHONVER/./}"
        pkgver=`cat exatomic/static/version.txt`
        sed -i "s/version = .* /version = \"${pkgver}\"/" meta.yaml
        cat meta.yaml
        conda build --no-include-recipe .
        basedir=/usr/share/miniconda/envs/test/conda-bld/linux-64
        conda convert -f -p osx-64 ${basedir}/exatomic-${pkgver}-${pyver}_0.tar.bz2 -o dist1/
        conda convert -f -p linux-32 ${basedir}/exatomic-${pkgver}-${pyver}_0.tar.bz2 -o dist1/
        conda convert -f -p win-32 ${basedir}/exatomic-${pkgver}-${pyver}_0.tar.bz2 -o dist1/
        conda convert -f -p win-64 ${basedir}/exatomic-${pkgver}-${pyver}_0.tar.bz2 -o dist1/
        ls -lisah dist1
        anaconda login --username ${{ inputs.conda-username }} --password ${{ inputs.conda-password }}
        anaconda upload --no-progress ${basedir}/exatomic-${pkgver}-${pyver}_0.tar.bz2
        for pkg in $(ls -d dist1/*/); do
          echo "${pkg}exatomic-${ver}-${pyver}_0.tar.bz2"
          anaconda upload --no-progress ${pkg}exatomic-${ver}-${pyver}_0.tar.bz2
        done
